name: Daily AGVCH Check

on:
  schedule:
    - cron: "0 6 * * *"  # runs daily at 06:00 UTC
  workflow_dispatch:

jobs:
  check-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute Notebook
        run: |
          jupyter nbconvert --to notebook --execute checker.ipynb --stdout > /dev/null

      - name: Commit generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add current_munies/*.csv summaries/*.json

          git commit -m "Update for $(date -u +"%Y-%m-%d")"
          git push